### ISSUE TITLE
Question: Vue-play not running after recent update

### ISSUE THREAD

**Issue by utkarshnag** [SSENSE/vue-carousel#282]
yarn build and yarn test is working. My system is Windows 10 (64 bit). @quinnlangille what to do?

$ yarn dev
yarn run v1.9.4
$ vue-play start --standalone
webpack: wait until bundle finished:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\vue-
play-cli\node_modules\express\lib\application.js:618:24)
    at module.exports (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\vue-p
lay-cli\lib\server.js:42:7)
    at module.exports (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\vue-p
lay-cli\bin\vue-play-start.js:12:3)
    at CAC.runCommand (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\vue-p
lay-cli\node_modules\cac\dist\cac.common.js:228:14)
    at CAC.parse (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\vue-play-c
li\node_modules\cac\dist\cac.common.js:283:8)
    at Object.<anonymous> (C:\Users\hp\Desktop\Forks\vue-carousel\node_modules\v
ue-play-cli\bin\vue-play.js:23:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by utkarshnag** [comment]
I just ended up deleting my fork. Forked and cloned this repo again and it works perfectly fine now. I will close this issue.

**Comment by quinnlangille** [comment]
Ah, it may have been an issue with one of the node modules since the web pack update changed a lot of versions. In that case, it's also useful to try to delete your node_modules folder and reinstall! Glad it's working now
