### ISSUE TITLE
Bug: yarn install && yarn run dev is broken

### ISSUE THREAD

**Issue by BRafols** [SSENSE/vue-carousel#442]
## Bug Report

**Current Behavior**
Console throws with the following error.

```
yarn run v1.16.0
$ vue-play start --standalone
webpack: wait until bundle finished: 
webpack built 3680b04343a5ea45f9ee in 2929ms
Hash: 3680b04343a5ea45f9ee
Version: webpack 1.15.0
Time: 2929ms
        Asset       Size  Chunks             Chunk Names
js/preview.js    1.12 MB       0  [emitted]  preview
    js/app.js    1.51 MB       1  [emitted]  app
   index.html  347 bytes          [emitted]  
 preview.html  351 bytes          [emitted]  

ERROR in ./play/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /home/borja/development/new_propertista/github-org/vue-carousel/node_modules/babel-preset-es2015/lib/index.js
    at createDescriptor (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/partial.js:57:55)
    at loadFullConfig (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/home/borja/development/new_propertista/github-org/vue-carousel/node_modules/vue-play-cli/node_modules/babel-loader/lib/index.js:46:20)
 @ ./~/vue-play-cli/lib/entries/preview.js 1:0-21
webpack: Failed to compile.

Compiled successfully!

Vue Play is running at http://localhost:5000

```

**Input Code and steps to reproduce**

1. Clone repo
2. `yarn install`
3. `yarn run dev`

**Expected behavior/code**
It should be able to run without errors

**Comment by Nfinished** [comment]
It's the `vue-play-cli` dev dependency, which still runs on webpack v1 (yikes). Its build process relies on `extract-text-webpack-plugin` (deprecated in favor of `mini-css-extract-plugin`). extract-text needs a webpack module called removeAndDo, which has been absolutely wiped off of the face of the earth. `vue-play-cli` and the vue-play project as a whole are phenomenally stale, best solution here may be to refactor the dev environment to no longer rely on them.

**Comment by quinnlangille** [comment]
Hey guys! Sorry for the delay here, there's a PR up to resolve this, will ping here once it's merged ~

**Comment by champi-dev** [comment]
@quinnlangille @Nfinished 
I'm facing this same issue.
Will this be fixed any time soon?

**Comment by jakkalas** [comment]
@quinnlangille @Nfinished I'm also facing this issue. I'd love to contribute to this project, but this is making it difficult to get it up and running

**Comment by Nfinished** [comment]
This repo seems pretty dead, I'd recommend taking a look at https://github.com/surmon-china/vue-awesome-swiper if you're in need of a carousel with this one's functionality + a lot more.

**Comment by honzabilek4** [comment]
> This repo seems pretty dead, I'd recommend taking a look at https://github.com/surmon-china/vue-awesome-swiper if you're in need of a carousel with this one's functionality + a lot more.

Thanks, this saved my day. 
We used this vue-carousel, but then had issues with SSR. So I cloned the repo with an intention to fix it, but I'm unable to run it in the dev mode. Also the repo seems pretty stale, so maybe a it's good idea to look somewhere else.
