### ISSUE TITLE
gridsome build error

### ISSUE THREAD

**Issue by nothinghalosix** [SSENSE/vue-carousel#569]
## (node:99081) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (/Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:24223)
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:21188
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394

**Comment by aleksanderwalczuk** [comment]
@nothinghalosix were you able to resolve this issue? I cannot build this with Gridsome

**Comment by nothinghalosix** [comment]
try this in your script

`export default {
  components: {
    Carousel: () =>
      import("vue-carousel")
        .then((m) => m.Carousel)
        .catch(),
    Slide: () =>
      import("vue-carousel")
        .then((m) => m.Slide)
        .catch(),
  },`

**Comment by aleksanderwalczuk** [comment]
Thanks for that, I actually solved it by setting a **client only** condition.

added as plugin in _main.js_
```js
  if (process.isClient) {
      Vue.use(require("vue-carousel").default);
}
```
_in template file_
```vue
<ClientOnly>
  <carousel>
    <slide>slide 1</slide>
  <carousel>
</ClientOnly>
```

**Comment by a-kriya** [comment]
Registering as a plugin did not work for me, but registering individual components in main.js fixed the builds for me:

```js
if (process.isClient) {
  Vue.component('Carousel', require('vue-carousel').Carousel)
  Vue.component('Slide', require('vue-carousel').Slide)
}
```

In the last few days, my Gridsome builds started erroring out. I was registering per-component earlier as @nothinghalosix shared. I do not know what the difference is with registering in main.js with `isClient` check but it has fixed my issue.
